add ERROR prefix

diff --git a/bin/build-control b/bin/build-control
--- a/bin/build-control
+++ b/bin/build-control
@@ -66,7 +66,7 @@ for FILE in $(cd $DISTRO > /dev/null && ls genome-snapshot-deps-*.depends); do
             echo "Description: This meta-package installs the LIMS-APipe bridge dependencies."
             ;;
         *)
-            echo "'$PKG' needs to be added to 'build-control' script." 1>&2
+            echo "ERROR: '$PKG' needs to be added to 'build-control' script." 1>&2
             exit 128
             ;;
     esac
